development:
  adapter: postgresql
  encoding: utf8
  database: local_vedrans_playground
  host: localhost
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  database: local_test_vedrans_playground
  host: localhost
  pool: 5
  username: myapp
  password: password1

production:
  adapter: postgresql
  encoding: utf8
  database: vedrans_playground
  host: localhost
  pool: 5
  username: rails
  password: secret
